# Generated by Django 3.2.19 on 2023-11-29 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='projectid',
            field=models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contract_UserRole', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='roleid',
            field=models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, related_name='Role_UserRole', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='User_UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permissionid',
            field=models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.PROTECT, related_name='Permission_RolePermission', to='accounts.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='roleid',
            field=models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, related_name='Role_RolePermission', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(through='accounts.UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ManyToManyField(through='accounts.RolePermission', to='accounts.Role'),
        ),
        migrations.AddField(
            model_name='pmrsuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='pmrsuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
