# Generated by Django 3.2.19 on 2024-07-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractCostCenter',
        ),
        migrations.DeleteModel(
            name='CostCenter',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
        migrations.RemoveField(
            model_name='overheadgroup',
            name='contractid',
        ),
        migrations.RemoveField(
            model_name='overheaditem',
            name='overheadgroupid',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='contractid',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='financialdocument',
        ),
        migrations.DeleteModel(
            name='ScheduleBackup',
        ),
        migrations.DeleteModel(
            name='ScheduleCellArchive',
        ),
        migrations.RemoveField(
            model_name='schedulefinancialdocument',
            name='documentid',
        ),
        migrations.RemoveField(
            model_name='schedulefinancialdocument',
            name='scheduleid',
        ),
        migrations.DeleteModel(
            name='OverheadGroup',
        ),
        migrations.DeleteModel(
            name='OverheadItem',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleFinancialDocument',
        ),
    ]
