# Generated by Django 3.2.19 on 2024-08-09 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='senddate',
            field=models.DateTimeField(blank=True, db_column='SendDate', default=datetime.date(2024, 8, 10), null=True),
        ),
    ]
