# Generated by Django 3.2.19 on 2023-11-30 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0002_auto_20231201_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportvisitdate',
            name='reportvisitdate',
            field=models.DateField(db_column='ReportVisitDate', default=django.utils.timezone.now),
        ),
    ]
