# Generated by Django 3.2.19 on 2024-07-14 05:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0003_alter_reportvisitdate_reportvisitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedinvoicedox',
            name='file',
            field=models.FileField(db_column='File', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contractordox',
            name='file',
            field=models.FileField(db_column='File', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Sub Contracts'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hsereportdox',
            name='file',
            field=models.FileField(db_column='File', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Hse_Reports'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectdox',
            name='file',
            field=models.FileField(db_column='File', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Contract'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='projectmonthlydox',
            name='file',
            field=models.FileField(db_column='File', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Project Monthly Reports'), unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img1',
            field=models.ImageField(blank=True, db_column='Img1', max_length=250, null=True, unique=True, upload_to='zone_images'),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img2',
            field=models.ImageField(blank=True, db_column='Img2', max_length=250, null=True, unique=True, upload_to='zone_images'),
        ),
        migrations.AlterField(
            model_name='zoneimage',
            name='img3',
            field=models.ImageField(blank=True, db_column='Img3', max_length=250, null=True, unique=True, upload_to='zone_images'),
        ),
    ]
