# Generated by Django 3.2.19 on 2024-07-14 08:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_files', '0004_auto_20240714_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedinvoicedox',
            name='file',
            field=models.FileField(db_column='File', max_length=250, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\projects\\cost_control\\Pmrs_Files\\Approved Invoices'), upload_to=''),
        ),
    ]
